server:
  port: 8080
spring:
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wangqiang
    password: 123456
    publisher-confirm-type: correlated #发送确认
    template:
      mandatory: true #发送失败触发回调
    publisher-returns: true #发送回调
    listener:
      simple:
        acknowledge-mode: manual #手动确认
logging:
  config: classpath:logback-spring.xml
